---
- name: "Configure and Backup Switches"
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
     - name: Name vlan 10 and 20
       cisco.ios.ios_config:
         lines:
           - vlan 10
           - name Management
           - vlan 20
           - name Sales
         #save_when: modified

     - name: Run the show commands
       ios_command:
         commands:
         - show clock
         - show hosts
         - show int status | inc connected
         - show vlan brief
         - show spanning-tree active
         - show mac address-table dynamic
       register: show_output

     - name: Save switch outputs to backups folder
       copy:
           content: "{{ show_output.stdout| to_nice_yaml(indent=2, width=80) }}"
           dest: "backups/{{ inventory_hostname }}-config.txt"
...
