---
- name: "Configure a Loopback"
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Create Loopback
      ios_config:
        lines:
          - interface Loopback0
          - description Configured by Ansible
          - ip address {{ loopback }} 255.255.255.255
        parents: interface Loopback0
      when: loopback is defined
      register: config_result

    - name: Display Loopback
      debug:
        msg: "The loopback 0 IP address for {{ inventory_hostname }} is {{loopback }}."
      when: loopback is defined

    - name: Show Interface Status
      ios_command:
        commands:
         - show ip interface brief | include up
      register: show_output

    - name: Save outputs to backups folder
      copy:
        content: "{{ show_output.stdout| to_nice_yaml(indent=2, width=80) }}"
        dest: "backups/{{ inventory_hostname }}-loopback-config.txt"
      when: show_output.stdout[0] is defined
...
